services:
  app:
    image: wordpress-codespace:8.1-apache-bullseye
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
  mysql:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=wordpress
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 81:80
    environment:
      PMA_HOST: mysql
volumes:
  mysql: